Changes in app
AlisaSogrina/Spring-Project pull request #1
Opened 2022-12-06 21:24 UTC by AlisaSogrina

Here are some new features like lists of users and projects

2022-12-07 09:19 UTC, ArseniyTy requested changes

2022-12-07 09:19 UTC, ArseniyTy commented on src/main/java/by/alisa/cource/repository/ProjectsRepository.java
> +    Iterable<Project> findAllByTextContainsIgnoreCase(String value);
Этот метод вроде не нужен. И в сервисе лежит метод, вызывающий данный, там он тоже не нужен

2022-12-07 09:19 UTC, ArseniyTy commented on src/main/java/by/alisa/cource/service/ProjectsService.java
> +        project.setText(project.getText());
Видимо здесь хотелось что-то другое. Потому что объект `project` устанавливает значение своего поля в такое же значение - равносильно ничего не деланию

2022-12-07 09:19 UTC, ArseniyTy commented on src/main/resources/templates/project.html
> +<h1>Delete</h1>
Вообще этот заголовок не нужен. На кнопке же уже написано delete. Но это ладно, при написании стилей это будет и так понятно думаю

2022-12-07 09:19 UTC, ArseniyTy commented on src/main/resources/templates/projects.html
>  <a>Create project</a>
Почему тег ссылки, а не заголовка или чего-то еще?

2022-12-07 12:45 UTC, AlisaSogrina commented on src/main/java/by/alisa/cource/repository/ProjectsRepository.java
> +    Iterable<Project> findAllByTextContainsIgnoreCase(String value);
Ну это пока не нужен, а скоро будет нужен
Неужели он мешает

2022-12-07 12:48 UTC, AlisaSogrina commented on src/main/resources/templates/projects.html
>  <a>Create project</a>
Добавление файла css, а как еще(

2022-12-08 09:15 UTC, ArseniyTy commented on src/main/java/by/alisa/cource/repository/ProjectsRepository.java
> +    Iterable<Project> findAllByTextContainsIgnoreCase(String value);
Ну если потом будет нужен, то ладно, но можно было бы хотя бы закомментить)

2022-12-08 09:16 UTC, ArseniyTy commented on src/main/resources/templates/projects.html
>  <a>Create project</a>
Ой, не к тому добавился комментарий. Я про 10-ую строчку, где `<a>Create project</a>`

2022-12-10 22:18 UTC, ArseniyTy commented on src/main/resources/templates/project.html
> +<p>          </p>
?

2022-12-10 22:18 UTC, ArseniyTy commented on src/main/resources/templates/project.html
> +        <button class="button button1" type="submit">Delete</button>
Классы стоит называть понятнее, а не `button`, `button1`, `button1234`

2022-12-12 17:08 UTC, ArseniyTy approved these changes

2023-04-04 23:46 UTC, merged